import numpy as np
a = np.array([1, 2, 3, 4])
a += 1
print(a)
a = np.array([1, 2, 3, 4])
a **= 2
print(a)
b = np.ones(4) + 1
print(b)
a = np.array([1, 2, 3, 4])
print(a-b)
print(a*b)
c = np.diag([1, 2, 3, 4])
print(c*c)
print("++++++++++++++++++++++++++++")
print(c.dot(c))
c = np.array(a == b)
print(c)
a = np.arange(5)
print(np.sin(a))
# print(np.log(a))
print(np.exp(a))

x = np.array([1, 2, 3, 4])
# print(x.sum())
print(np.sum(x))
x = np.array([[1, 1], [2, 2]])
print(x.sum(axis=0))
print(x.sum(axis=1))

x = np.array([1, 5, 7, 10, 2])
print(x.min())
print(x.max())
print(x.argmax())
print(x.argmin())

a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
print(((a <= b) & (b <= c)).all())
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
print(((a <= b) & (b <= c)).all())
